module.exports = {
	'🏙️': 'lucknow',
	'🕌': 'prayagraj',
	'🏛️': 'delhi',
	'🌇': 'bangalore',
	'🌊': 'mumbai',
	'📚': 'kolkata',
	'🌴': 'chennai',
	'🌶️': 'hyderabad',
	'🏭': 'kanpur',
	'🗺️': 'other-city',
	'💻': 'dev',
	'🎨': 'design',
	'🔬': 'research',
	'⚙️': 'ops',
};
